### ISSUE TITLE
Add pre-built Cython code to the source distribution.

### ISSUE THREAD

**Issue by ChrisBarker-NOAA** [NOAA-ORR-ERD/cell_tree2d#3]
THis would allow folks to built it without Cython (or a particular Cyton version).

I'm not totally sure that that's worth it -- once you've got numpy and a compiler, cyton is not a heavy lift, but it is how some folks distribute similar packages.

**Comment by ChrisBarker-NOAA** [comment]
maybe hard to do with py2/py3 -- #4

**Comment by MuellerSeb** [comment]
Should be solved with #15

Cython can be specified as a build time dependency when using a pyproject.toml file. And when using pre-built wheels cython is not needed at all.

**Comment by ChrisBarker-NOAA** [comment]
exactly -- no need to include source. compiling is harder than running Cython :-)
