### ISSUE TITLE
API clean up?

### ISSUE THREAD

**Issue by ChrisBarker-NOAA** [NOAA-ORR-ERD/cell_tree2d#7]
I noticed that there is:

`CellTree.find_poly()`

and

`CelTree.multi_locate`

these should either be merged -- allow multi-locate to take a single point (and jsut cal it locate, or ??)

or at least give them similar names.

**Comment by jay-hennen** [comment]
This has been done. Now use CellTree.locate(points) and it should work for singular, lists, tuples, arrays, whatever. I've also moved the vectorization from cython into C, for quite a major speedup, apparently, and renamed several functions in the C as well

**Comment by ChrisBarker-NOAA** [comment]
great, thanks!

I wonder why the cython looping was slower? but whatever we're using C anyway, so why not?

**Comment by jay-hennen** [comment]
The loop was slower because there was just quantitatively more generated C code within the loop itself. Difference between calling a function once versus 70k times.

**Comment by ChrisBarker-NOAA** [comment]
ah, got it -- calling a function in a loop, rather than doing the actual work in the loop (kinds like inlining)
